[package]
name = "rust_tokio_overhead"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "6"
tokio = {version = "1", features=["rt", "rt-multi-thread"]}
rand = "0.8.4"